# Generated by Django 5.0.4 on 2024-05-04 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0006_alter_usuario_email_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='reputacion',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='apptrueques.categoria'),
            preserve_default=False,
        ),
    ]
