# Generated by Django 5.0.4 on 2024-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0008_remove_comentario_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('PUBLICADA', 'Publicada'), ('PENDIENTE', 'Pendiente'), ('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida')], default='PUBLICADA', max_length=20),
        ),
    ]
