# Generated by Django 5.0.4 on 2024-05-07 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0009_publicacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sucursal_favorita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='apptrueques.sucursal'),
            preserve_default=False,
        ),
    ]
