# Generated by Django 5.0.6 on 2024-05-12 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0013_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sucursal_favorita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='apptrueques.sucursal'),
        ),
    ]
