# Generated by Django 5.0.6 on 2024-05-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0017_alter_empleado_options_alter_empleado_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
