# Generated by Django 5.0.6 on 2024-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0019_alter_empleado_options_alter_empleado_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='', max_length=150),
        ),
    ]
