# Generated by Django 5.0.6 on 2024-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0020_empleado_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='user',
        ),
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
