# Generated by Django 5.0.6 on 2024-05-23 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0021_remove_empleado_user_empleado_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal_de_trabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='apptrueques.sucursal'),
        ),
    ]
