# Generated by Django 5.0.6 on 2024-05-23 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0022_empleado_is_staff_empleado_sucursal_de_trabajo'),
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(default='', max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='apptrueques.empleado')),
            ],
            bases=('authtoken.token',),
        ),
    ]
