# Generated by Django 5.0.6 on 2024-05-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0023_remove_empleado_id_alter_empleado_dni_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
