# Generated by Django 5.0.6 on 2024-05-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0024_alter_publicacion_fecha_delete_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentariorespuesta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
