# Generated by Django 5.0.6 on 2024-05-27 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0025_alter_comentario_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='estado',
        ),
        migrations.CreateModel(
            name='SolicitudDeIntercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ESPERANDO', 'Esperando'), ('PENDIENTE', 'Pendiente'), ('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida')], default='ESPERANDO', max_length=20)),
                ('publicacion_a_intercambiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to='apptrueques.publicacion')),
                ('publicacion_deseada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='apptrueques.publicacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
