# Generated by Django 5.0.6 on 2024-05-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0026_remove_publicacion_estado_solicituddeintercambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeintercambio',
            name='estado',
            field=models.CharField(choices=[('ESPERA', 'Espera'), ('PENDIENTE', 'Pendiente'), ('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida')], default='ESPERA', max_length=20),
        ),
    ]
