# Generated by Django 5.0.6 on 2024-05-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0027_alter_solicituddeintercambio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddeintercambio',
            name='fecha_del_intercambio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
