# Generated by Django 5.0.6 on 2024-06-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0028_solicituddeintercambio_fecha_del_intercambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
