# Generated by Django 5.0.6 on 2024-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0030_alter_empleado_options_alter_empleado_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
