# Generated by Django 5.0.6 on 2024-06-05 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0032_producto_venta_publicacion_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='publicacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='apptrueques.publicacion'),
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='ventas', to='apptrueques.producto'),
        ),
    ]
