# Generated by Django 5.0.6 on 2024-06-06 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0033_remove_publicacion_venta_venta_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(related_name='ventas', to='apptrueques.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='publicacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='apptrueques.solicituddeintercambio'),
        ),
    ]
