# Generated by Django 5.0.6 on 2024-06-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0035_alter_producto_cantidad_vendida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.AddField(
            model_name='venta',
            name='productos_vendidos',
            field=models.ManyToManyField(related_name='ventas', to='apptrueques.producto'),
        ),
    ]
