# Generated by Django 5.0.6 on 2024-06-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0036_remove_venta_productos_venta_productos_vendidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='productos_vendidos',
            new_name='productos',
        ),
    ]
