# Generated by Django 5.0.6 on 2024-06-07 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0037_rename_productos_vendidos_venta_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='publicacion',
            new_name='intercambio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_vendida',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrueques.producto')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='productos_vendidos',
            field=models.ManyToManyField(related_name='ventas', to='apptrueques.ventaproducto'),
        ),
    ]
