# Generated by Django 5.0.6 on 2024-06-26 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0038_rename_publicacion_venta_intercambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fecha_fin_promocion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sucursal_de_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='apptrueques.sucursal'),
        ),
    ]
