# Generated by Django 5.0.6 on 2024-06-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0040_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(default='noPostImage.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(default='userNoProfilePicture.jpg', upload_to='images'),
        ),
    ]
