# Generated by Django 5.0.6 on 2024-06-27 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0041_alter_publicacion_imagen_alter_usuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=200)),
                ('leida', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(default='/images/noPostImage.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(default='/images/userNoProfilePicture.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='apptrueques.notificacion'),
        ),
    ]
