# Generated by Django 5.0.6 on 2024-06-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0042_notificacion_alter_publicacion_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='notificacion',
            new_name='notificaciones',
        ),
    ]
