# Generated by Django 5.0.6 on 2024-06-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0043_rename_notificacion_usuario_notificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='notificaciones',
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificaciones',
            field=models.ManyToManyField(related_name='usuarios', to='apptrueques.notificacion'),
        ),
    ]
