# Generated by Django 5.0.6 on 2024-06-29 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0044_remove_usuario_notificaciones_usuario_notificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='notificaciones',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
