# Generated by Django 5.0.6 on 2024-07-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0046_notificacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='borrada',
            field=models.BooleanField(default=False),
        ),
    ]
