# Generated by Django 5.0.6 on 2024-07-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrueques', '0048_alter_solicituddeintercambio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeintercambio',
            name='estado',
            field=models.CharField(choices=[('ESPERA', 'Espera'), ('PENDIENTE', 'Pendiente'), ('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida'), ('RECHAZADA', 'Rechazada')], default='ESPERA', max_length=20),
        ),
    ]
